server:
  port: 9000

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8090/eureka

spring:
  cloud:
    gateway:
      discovery:
        locator:
          enable: true
      routes:
        - id: servicio-cliente
          uri: lb://servicio-cliente
          predicates:
            - Path=/clientes/**
        - id: servicio-compra
          uri: lb://servicio-compra
          predicates:
            - Path=/compras/**

        - id: servicio-producto
          uri: lb://servicio-producto
          predicates:
            - Path=/categorias/**, /productos/**

        #========servicio pedido=======#
        - id: servicio-pedido
          uri: lb://servicio-pedido
          predicates:
            - Path=/pedido/**

        # La rama de ventas (nelson)
        - id: servicio-venta
          uri: lb://servicio-venta
          predicates:
            - Path=/ventas/**, /ventasdetalle/**, /comprobantes/**
        # ============================================
        - id: servicio-proveedor
          uri: lb://servicio-proveedor
          predicates:
            - Path=/proveedores/**
        # ============================================