server:
  port: 9000

eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8090/eureka}
  instance:
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
spring:
  cloud:
    gateway:
      discovery:
        locator:
          enable: true
      routes:
        #========servicio proveedor========#
        - id: servicio-proveedor
          uri: lb://servicio-proveedor
          predicates:
            - Path=/proveedores/**, /productos-proveedores/**, /compras-proveedores/**, /detalle_compras/**

        #=========servicio inventario=======#
        - id: servicio-inventario
          uri: lb://servicio-inventario
          predicates:
            - Path=/inventario/**, /ajustes_inventario/**, /movimientos_inventario/**

        #========servicio cliente========#
        - id: servicio-cliente
          uri: lb://servicio-cliente
          predicates:
            - Path=/clientes/**

        #========servicio producto========#
        - id: servicio-producto
          uri: lb://servicio-producto
          predicates:
            - Path=/categorias/**, /productos/**, /producto-disponible/**


        #========servicio pedido=======#
        - id: servicio-pedido
          uri: lb://servicio-pedido
          predicates:
            - Path=/pedido/**
