server:
  port: 8081

springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true
    path: /doc/swagger-ui.html

spring:
  jpa:
    hibernate.ddl-auto: update
    generate-ddl: true
    show_sql: true
    datasource:
      driverClassName: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://localhost:3306/proveedor_db
      username: root
      password:

  cloud:
    gateway:
      discovery:
        locator:
          enable: true
      routes:
        - id: servicio-proveedor
          uri: lb://SERVICIO-PROVEEDOR
          predicates:
            - Path=/proveedores/**

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8080/eureka
  instance:
    hostname: localhost
