server:
  port: 9000

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8090/eureka

spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true

      routes:
        - id: servicio-inventario
          uri: lb://SERVICIO-INVENTARIO
          predicates:
            - Path=/inventario/**
