server:
  port: 9000

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8090/eureka

spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true

      routes:
      #===========servicio inventario==========#
        - id: servicio-inventario
          uri: lb://servicio-inventario
          predicates:
            - Path=/inventario/**, /ajustes_inventario/**, /movimientos_inventario/**
      #==========servicio proveedor===========#
        - id: servicio-proveedor
          uri: lb://servicio-proveedor
          predicates:
            - Path=/proveedores/**, /productos-proveedores/**, /compras-proveedores/**, /detalle_compras/**
        #========servicio producto========#
        - id: servicio-producto
          uri: lb://servicio-producto
          predicates:
            - Path=/categorias/**, /productos/**
