server:
  port: 5001  # Puerto donde corre el servicio de proveedores
  # Puedes poner cualquier otro puerto si es necesario.

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/proveedor_db
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: password  # Cambia según tus credenciales
  jpa:
    hibernate.ddl-auto: update
    database-platform: org.hibernate.dialect.MySQL8Dialect

eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8080/eureka}  # Cambia la URL según la dirección de tu Eureka
  instance:
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
    hostname: localhost
    # Otros parámetros de instancia si lo necesitas
