server:
  port: 9000

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8090/eureka

spring:
  cloud:
    gateway:
      discovery:
        locator:
<<<<<<< HEAD
          enable: true
      routes:
        #========servicio proveedor========#
        - id: servicio-proveedor
          uri: lb://servicio-proveedor
          predicates:
            - Path=/proveedores/**, /productos-proveedores/**, /compras-proveedores/**, /detalle_compras/**
=======
          enabled: true
>>>>>>> pastor

      routes:

        #===========servicio inventario==========#
        - id: servicio-inventario
          uri: lb://servicio-inventario
          predicates:
            - Path=/inventario/**, /ajustes_inventario/**, /movimientos_inventario/**
<<<<<<< HEAD

        #========servicio cliente========#
        - id: servicio-cliente
          uri: lb://servicio-cliente
          predicates:
            - Path=/clientes/**

=======
        #==========servicio proveedor===========#
        - id: servicio-proveedor
          uri: lb://servicio-proveedor
          predicates:
            - Path=/proveedores/**, /productos-proveedores/**, /compras-proveedores/**, /detalle_compras/**
>>>>>>> pastor
        #========servicio producto========#
        - id: servicio-producto
          uri: lb://servicio-producto
          predicates:
<<<<<<< HEAD
            - Path=/categorias/**, /productos/**, /producto-disponible/**


        #========servicio pedido=======#
        - id: servicio-pedido
          uri: lb://servicio-pedido
          predicates:
            - Path=/pedido/**
=======
            - Path=/categorias/**, /productos/**
>>>>>>> pastor
