server:
  port: 7070

spring:
  application:
    name: servicio_configuracion
  cloud:
    config:
      server:
        git:
          uri: https://github.com/jhosue-pstr/AquiNomas.git
          searchPaths: config-data
          default-label: moises
  security:
    user:
      name: root
      password: 123456
