#spring.application.name=servicio-gateway

spring:
  application:
    name: servicio-gateway
  profiles:
    active: development
  config:
    import: optional:configserver:http://root:123456@localhost:7070
