#spring.application.name=servicio-descubrimiento


spring:
  application:
    name: servicio-descubrimiento
  profiles:
    active: development
  config:
    import: optional:configserver:http://root:123456@localhost:7070